extends: eslint:recommended

env:
  es6: true
  browser: true

parser:
  babel-eslint

plugins: [
  react
]

parserOptions:
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  no-unused-vars: error
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1