export const SELECT_INGREDIENTS = 'SELECT_INGREDIENTS'
export const FIND_INGREDIENT = 'FIND_INGREDIENT'

export const CHANGE_CALORIES_VALUE = 'CHANGE_CALORIES_VALUE'

export const UPDATE_SMOOTHIES_LIST = 'UPDATE_SMOOTHIES_LIST'

export const SHOW_SNACKBAR = 'SHOW_SNACKBAR'
export const HIDE_SNACKBAR = 'HIDE_SNACKBAR'
